import type { Metadata } from "next";
import { poppins } from "./utils/Fonts";
import "./globals.css";
import { ThemeProvider } from 'next-themes';
import ThemeWrapper from "./containers/ThemeWrapper";
import Navbar from "./components/Navbar/Navbar";
import ReduxProvider from "./providers/ReduxProviders";
import MountedClient from "./containers/MountedClient";
import ToastProvider from "./providers/ToastProviders";
import { ReactNode } from "react";
import { fetchCurrentUser, User } from "./actions/getCurrentUser";
import UserContextProvider from "@/app/providers/UserProvider"; // Import the context provider
import { NextAuthProvider } from "./providers/NextAuthProvider";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const user = await fetchCurrentUser()
  // console.log("Layout: ", user)

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <title>Kartal Chat App</title>
        <link rel="shortcut icon" href="/kartal_icon.svg" type="image/x-icon" />
      </head>
      <body className={`${poppins.className} bg-main h-screen w-full`}>
        <ReduxProvider>

          <MountedClient>
            <ThemeProvider attribute="class" enableSystem={true}>
              <ThemeWrapper>
                <ToastProvider />

                <NextAuthProvider>
                  <Navbar user={user} />
                  {children}
                </NextAuthProvider>

              </ThemeWrapper>
            </ThemeProvider>
          </MountedClient>

        </ReduxProvider>
      </body>
    </html>
  );
}



